 proma-working-code
# Generated by Django 6.0.6 on 2026-08-03 06:50


# Generated by Django 6.0.6 on 2026-07-08 15:41

import django.db.models.deletion
from django.conf import settings
 main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
 proma-working-code

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
 main
    ]

    operations = [
        migrations.CreateModel(
 proma-working-code
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),

            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Dhaka", max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "Full House"),
                            ("room", "Single Room"),
                            ("mess", "Mess/Sublet"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
 main
            ],
        ),
    ]
