# Generated by Django 6.0.6 on 2026-08-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
