# Generated by Django 6.0.6 on 2026-08-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
