# Generated by Django 6.0.6 on 2026-08-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_property_latitude_property_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bKash", "bKash"),
                    ("Nagad", "Nagad"),
                    ("Rocket", "Rocket"),
                    ("Cash", "Cash"),
                ],
                default="bKash",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(default="NOT_PROVIDED", max_length=100),
            preserve_default=False,
        ),
    ]
