# Generated by Django 6.1 on 2026-08-23 04:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
